package net.ethobat.system0.api.recipe;

public enum S0RecipeType {

    DISTHUSIATION,
    WIREFRAME_BLENDING,
    PLANAR_REDUCTION,
    POWDER_AGGLOMERATION,
    PRECISION_LASERIZATION,
    EXOTICIZATION,
    MAGIC_CORPOREALIZATION,
    THOUGHTFORM_METAREACTION,
    SINATION_COSINATION,
    DIFFERENTIATION,
    INTEGRATION,
    RECIPROCAL_INVERSION,
    CONTRASYNTHESIS,
    ZEE_COMBING,

}
